- PopulationLib/GroupPlanting.py
- PopulationLib/Population.py
- PopulationLib/Species/Avicennia.py
- PopulationLib/Species/__init__.py
- PopulationLib/Tree.py
- PopulationLib/TreeGroup.py
- PopulationLib/__init__.py
- ProjectLib/Project.py
- ProjectLib/XMLtoProject.py
- ProjectLib/__init__.py
- ProjectLib/testproject.xml
- TimeLoopLib/SimpleTimeLoop/SimpleLoop.py
- TimeLoopLib/TreeDynamicTimeLoop.py
- TimeLoopLib/TreeDynamicTimeStepping.py
- TimeLoopLib/__init__.py
- TreeModelLib/AbovegroundCompetition/AbovegroundCompetition.py
- TreeModelLib/AbovegroundCompetition/SimpleTest/SimpleTest.py
- TreeModelLib/AbovegroundCompetition/SimpleTest/__init__.py
- TreeModelLib/AbovegroundCompetition/__init__.py
- TreeModelLib/BelowgroundCompetition/BelowgroundCompetition.py
- TreeModelLib/BelowgroundCompetition/SimpleTest/SimpleTest.py
- TreeModelLib/BelowgroundCompetition/SimpleTest/__init__.py
- TreeModelLib/BelowgroundCompetition/__init__.py
- TreeModelLib/GrowthAndDeathDynamics/GrowthAndDeathDynamics.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleTest/SimpleTest.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleTest/__init__.py
- TreeModelLib/GrowthAndDeathDynamics/__init__.py
- TreeModelLib/__init__.py
- __init__.py
- main.py
This is quite a big PR - sorry
The PR contains
- TreeModelLib:
Module containing tree functionalities as Aboveground- and Belowgroundcompetition and the growth concepts
For all three submodules, simple test scenarios are created as discussed.
The argument stucture for the Competitions is as follows: assessing the tree positions, geometry and parameters the concept is able to calculate the resources for each individual
GrowthAndDeathDynamics are using the calculated resources in order to update tree geometry and parameters
Order of Function-calls per timestep is given in the TimeLoopLib
- PopulationLib:
Module which structures the tree population into groups. For each group, a species can be defined. Hereby, we keep the structure flexible. As an example, Bettina configurations are passed …
> Initial pull request

- PopulationLib/GroupPlanting.py
- PopulationLib/Population.py
- PopulationLib/Tree.py
- PopulationLib/TreeGroup.py
- PopulationLib/__init__.py
- ProjectLib/Project.py
- ProjectLib/XMLtoProject.py
- ProjectLib/__init__.py
- TimeLoopLib/SimpleTimeLoop/SimpleLoop.py
- TimeLoopLib/SimpleTimeLoop/__init__.py
- TimeLoopLib/TreeDynamicTimeLoop.py
- TimeLoopLib/TreeDynamicTimeStepping.py
- TimeLoopLib/__init__.py
- TreeModelLib/AbovegroundCompetition/AbovegroundCompetition.py
- TreeModelLib/AbovegroundCompetition/SimpleTest/SimpleTest.py
- TreeModelLib/AbovegroundCompetition/SimpleTest/__init__.py
- TreeModelLib/AbovegroundCompetition/__init__.py
- TreeModelLib/BelowgroundCompetition/BelowgroundCompetition.py
- TreeModelLib/BelowgroundCompetition/SimpleTest/SimpleTest.py
- TreeModelLib/BelowgroundCompetition/SimpleTest/__init__.py
- TreeModelLib/BelowgroundCompetition/__init__.py
- TreeModelLib/GrowthAndDeathDynamics/GrowthAndDeathDynamics.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleTest/SimpleTest.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleTest/__init__.py
- TreeModelLib/GrowthAndDeathDynamics/__init__.py
- TreeModelLib/TreeModel.py
- TreeModelLib/__init__.py
- __init__.py
- main.py
This PR is based on PR #1. Once #1 has been merged, this can be reviewed as well.
Changes here
- Import scheme for modules is updated
- A lot of classes now derive their functionalities from parents. E.g. Simple test <- BelowgroundCompetition <- TreeModel
in order to improve object oriented design
> Import structure, class heritage

- TimeLoopLib/TreeDynamicTimeStepping.py
> [TML] Bug fix in aboveground resources passing

- Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/SimpleBettina/c_SimpleBettina.md
- Documentation/project_dox/MangaProject/i_MangaProject.dox
- Documentation/project_dox/MangaProject/initial_population/group/distribution/Random/c_Random.dox
- Documentation/project_dox/MangaProject/tree_dynamics/i_tree_dynamics.dox
- Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/SimpleBettina/c_SimpleBettina.dox
- Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/i_tree_growth_and_death.dox
- Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/t_type.dox
- Documentation/project_dox/MangaProject/tree_time_loop/Simple/c_Simple.dox
- PopulationLib/Species/Avicennia.py
- TreeModelLib/GrowthAndDeathDynamics/GrowthAndDeathDynamics.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/__init__.py
- TreeModelLib/GrowthAndDeathDynamics/__init__.py
Bettina seems to do what it is expected to do. That's nice. I am convinced there is still reason for some constructive critical comments. Regarding whatever. Please feel free to do so. Thanx! In advance!
Have a nice Feierday!
Zaphod BX.
> Pybettina2

- .gitignore
- Documentation/ProjectFile/MangaProject/tree_output/NONE/c_NONE.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/c_OneTreeOneFile.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/s_geometry_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/s_output_each_nth_timestep.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/s_parameter_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/s_working_directory.md
- Documentation/ProjectFile/MangaProject/tree_output/i_tree_output.md
- Documentation/ProjectFile/MangaProject/tree_output/t_type.md
- Documentation/project_dox/MangaProject/i_MangaProject.dox
- Documentation/project_dox/MangaProject/tree_output/NONE/c_NONE.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/c_OneTreeOneFile.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/s_geometry_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/s_output_each_nth_timestep.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/s_parameter_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/s_working_directory.dox
- Documentation/project_dox/MangaProject/tree_output/i_tree_output.dox
- Documentation/project_dox/MangaProject/tree_output/t_type.dox
- PopulationLib/Tree.py
- ProjectLib/Project.py
- ProjectLib/XMLtoProject.py
- ProjectLib/testproject.xml
- TimeLoopLib/TreeDynamicTimeLoop.py
- TimeLoopLib/TreeDynamicTimeStepping.py
- TreeOutputLib/NONE/NONE.py
- TreeOutputLib/NONE/__init__.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
- TreeOutputLib/OneTreeOneFile/__init__.py
- TreeOutputLib/TreeOutput.py
- TreeOutputLib/__init__.py
As discussed with @zaphod-bx this creates an output for the simulation. For each tree, one file is created
> Output generation added

- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/c_SimpleAsymmetricZOI.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/s_x_1.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/s_x_2.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/s_x_resolution.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/s_y_1.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/s_y_2.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/aboveground_competition/SimpleAsymmetricZOI/s_y_resolution.md
- TreeModelLib/AbovegroundCompetition/AbovegroundCompetition.py
- TreeModelLib/AbovegroundCompetition/SimpleAsymmetricZOI/SimpleAsymmetricZOI.py
- TreeModelLib/AbovegroundCompetition/SimpleAsymmetricZOI/__init__.py
- TreeModelLib/AbovegroundCompetition/__init__.py
sooooooooooo,
this may work! check it out now!
> Above ground zoi

- Documentation/ProjectFile/MangaProject/initial_population/group/distribution/s_n_recruitment_per_step.md
- Documentation/project_dox/MangaProject/initial_population/group/distribution/i_distribution.dox
- Documentation/project_dox/MangaProject/initial_population/group/distribution/s_n_recruitment_per_step.dox
- PopulationLib/GroupPlanting.py
- ProjectLib/testproject.xml
- TimeLoopLib/TreeDynamicTimeStepping.py
Implementation of Tree recruitment as an optional input parameter
> Tree recruitment

- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/c_FON.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_aa.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_bb.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_fmin.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_salinity.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_x_1.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_x_2.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_x_resolution.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_y_1.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_y_2.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FON/s_y_resolution.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/SimpleKiwi/c_SimpleKiwi.md
- PopulationLib/Species/Avicennia.py
- TreeModelLib/BelowgroundCompetition/BelowgroundCompetition.py
- TreeModelLib/BelowgroundCompetition/FON/FON.py
- TreeModelLib/BelowgroundCompetition/FON/__init__.py
- TreeModelLib/GrowthAndDeathDynamics/GrowthAndDeathDynamics.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleKiwi/SimpleKiwi.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleKiwi/__init__.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
> Fon und kiwi

- main.py
> Parse input file

- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/c_OneTimestepOneFile.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/s_geometry_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/s_output_each_nth_timestep.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/s_parameter_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/s_working_directory.md
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/c_OneTimestepOneFile.dox
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/s_geometry_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/s_output_each_nth_timestep.dox
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/s_parameter_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/s_working_directory.dox
- Documentation/project_dox/MangaProject/tree_output/i_tree_output.dox
- Documentation/project_dox/MangaProject/tree_output/t_type.dox
- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTimestepOneFile/__init__.py
- TreeOutputLib/TreeOutput.py
This output case writes all tree data at each predefined timestep in one file.
> Output type: one file per timestep

- TreeModelLib/BelowgroundCompetition/OGSLargeScale3D/OGSLargeScale3D.py
pvd collection for the salinity distribution vtu files  at bettina timesteps is created automatically
> [TML/BC/OGS] pvd-creator

- Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/SimpleBettina/c_SimpleBettina.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/SimpleKiwi/c_SimpleKiwi.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/SimpleTest/c_SimpleTest.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/s_growth_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/s_growth_output.md
- Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/SimpleBettina/c_SimpleBettina.dox
- Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/SimpleKiwi/c_SimpleKiwi.dox
- Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/SimpleTest/c_SimpleTest.dox
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/c_OneTimestepOneFile.dox
- Documentation/project_dox/MangaProject/tree_output/OneTimestepOneFile/s_growth_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/c_OneTreeOneFile.dox
- Documentation/project_dox/MangaProject/tree_output/OneTreeOneFile/s_growth_output.dox
- PopulationLib/Tree.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
As requested:
With this PR we can extract predefined output information from GAAD-concept to output. This will be extended by ag and bg competition later.
So far, I added options to output ag and bg resources available for growth and the resistances.
> growth information for output

- Documentation/ProjectFile/MangaProject/initial_population/group/t_species.md
- Documentation/project_dox/MangaProject/initial_population/group/t_species.dox
- PopulationLib/Tree.py
Functionality to provide a custom species file similar to "Avicennia.py" is implemented in this PR.
> Custom species functionality

- TreeOutputLib/NONE/NONE.py
- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
- TreeOutputLib/TreeOutput.py
This allows to access the outputtyp for subroutines.
> [TOL] getOutputType Attribute added

- Documentation/ProjectFile/MangaProject/random_seed/s_random_seed.md
- Documentation/project_dox/MangaProject/i_MangaProject.dox
- Documentation/project_dox/MangaProject/random_seed/s_random_seed.dox
- ProjectLib/Project.py
- ProjectLib/XMLtoProject.py
- test/SmallTests/Test_Setups_small/FIXEDSAL_BETTINA.xml
This PR provides functionality to add a seed for random number generation.
I also updated one example file in order to show, how the update is supposed to work & and tested this file.
Please review
> Seed for random numbers

- test/LargeTests/Test_Setups_large/OGS3D_SAZOI_BETTINA.xml
- web/content/de/_index.html
Two commits with error corrections
> Error correction

- web/content/de/docs/Erste_Schritte/Erste_Anwendungen_von_pyMANGA.md
- web/content/de/docs/Erste_Schritte/Installation.md
- web/content/en/docs/getting_started/First_applications_of_pyMANGA.md
- web/content/en/docs/getting_started/Installation.md
- Added instructions for installing OGS and calculating LargeTests
- related changes in the general structure in web/content/doc/de/Erste_Schritte
What do you think about a description in this style? Is that sufficient or should I describe it in detail or add pictures?
**last spelling check and other pending, please do not merge yet**
> Changes web/content/doc/de:

- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/c_FixedSalinity.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/s_max_x.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/s_min_x.md
- Documentation/ProjectFile/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/s_salinty.md
- Documentation/project_dox/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/c_FixedSalinity.dox
- Documentation/project_dox/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/s_max_x.dox
- Documentation/project_dox/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/s_min_x.dox
- Documentation/project_dox/MangaProject/tree_dynamics/belowground_competition/FixedSalinity/s_salinty.dox
- TreeModelLib/BelowgroundCompetition/FixedSalinity/FixedSalinity.py
- test/SmallTests/Test_Setups_small/FIXEDSAL_BETTINA.xml
A salinity gradient is given as input. The concept now evaluates the salinity at each trees position
> Fixed salinity update

- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTimestepOneFilePerGroup/OneTimestepOneFilePerGroup.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
Bug: Eventually files were written to parent directory. Fixed now
Additionally: I output directory does not exist, it is created from now on...
> Bugfix in output

- web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
- web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
- Correction formatting
- No changes in content
- Should actually be able to merge immediately
> Changes in web/doc/exmouth:

- github/workflows/main.yml
- requirements.txt
Initalization of the auto unit test
> Initalization of the auto unit test

- .github/workflows/main.yml
Activate the automatic unit test on github
> activate the automatic unit test

- MANGA.py
- TimeLoopLib/ExternalDynamicTimeStepping.py
- TimeLoopLib/__init__.py
- TreeModelLib/BelowgroundCompetition/SimpleNetwork/SimpleNetwork.py
- TreeModelLib/BelowgroundCompetition/SimpleTest/SimpleTest.py
- TreeModelLib/TreeModel.py
- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTimestepOneFilePerGroup/OneTimestepOneFilePerGroup.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
- __init__.py
- test/SmallTests/Test_Setups_small/AllSimple.xml
This PR is giving functionality to use pyMANGA in python boundary conditions of OGS
It includes
- Class to allow for external modification of project
- New timestepper
- External accessibility
@jvollhueter could you please have a look what updates are required in you testscripts as main.py has been renamed...?
@mcwimm I think we need a simple bg-competition concept to test. Maybe we could start with the simple-test case?
> OGS compatibility

- Documentation/ProjectFile/MangaProject/tree_output/OneFile/c_OneFile.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_allow_previous_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_geometry_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_growth_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_network_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_output_each_nth_timestep.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_parameter_output.md
- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_working_directory.md
- Documentation/project_dox/MangaProject/tree_output/OneFile/c_OneFile.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_allow_previous_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_geometry_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_growth_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_network_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_output_each_nth_timestep.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_parameter_output.dox
- Documentation/project_dox/MangaProject/tree_output/OneFile/s_working_directory.dox
- Documentation/project_dox/MangaProject/tree_output/i_tree_output.dox
- Documentation/project_dox/MangaProject/tree_output/t_type.dox
- TreeOutputLib/OneFile/OneFile.py
- TreeOutputLib/OneFile/__init__.py
- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTimestepOneFilePerGroup/OneTimestepOneFilePerGroup.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
- TreeOutputLib/TreeOutput.py
- TreeOutputLib/__init__.py
A new output class (OneFile), which writes all desired outputs in one csv file, was added.
To simplify inheritance from the parent output class 'OneTimestep',  two new functions were added: 
- addSelectedHeadings: writes csv header 
- addSelectedOutputs: writes desired values to csv
All other output classes were updated.
> New output option 'OneFile'

- TreeModelLib/BelowgroundCompetition/NetworkFixedSalinity/NetworkFixedSalinity.py
- TreeModelLib/BelowgroundCompetition/SimpleNetwork/SimpleNetwork.py
- TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
There was a st*** bug in SimpleNetwork which led to the incorrect calculation of below-ground resources...
To avoid this in the future, I have updated all assignments of function arguments.
> Bug fix in SimpleNetwork

- PopulationLib/Tree.py
- TreeModelLib/BelowgroundCompetition/SimpleNetwork/SimpleNetwork.py
- TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
Add parameter `groupID` to network dictionary to use it as output variable
> New network parameter

- TreeModelLib/BelowgroundCompetition/NetworkFixedSalinity/NetworkFixedSalinity.py
- TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
Only minor changes in coding style (not functionality)
> Clarify inheritance

- TreeOutputLib/OneFile/OneFile.py
…to reduce number of variable declarations.
Functionality should be the same.
> [TOL] restructure OneFile class 

- Documentation/ProjectFile/MangaProject/tree_time_loop/Simple/s_n_step_ag.md
- Documentation/ProjectFile/MangaProject/tree_time_loop/Simple/s_n_step_bg.md
- Documentation/ProjectFile/MangaProject/tree_time_loop/Simple/s_n_step_gd.md
- Documentation/project_dox/MangaProject/tree_time_loop/Simple/c_Simple.dox
- Documentation/project_dox/MangaProject/tree_time_loop/Simple/s_n_step_ag.dox
- Documentation/project_dox/MangaProject/tree_time_loop/Simple/s_n_step_bg.dox
- Documentation/project_dox/MangaProject/tree_time_loop/Simple/s_n_step_gd.dox
- MANGA.py
- TimeLoopLib/ExternalDynamicTimeStepping.py
- TimeLoopLib/SimpleTimeLoop/SimpleLoop.py
- TimeLoopLib/TreeDynamicTimeLoop.py
- TimeLoopLib/TreeDynamicTimeStepping.py
This time stepper can be used externally and allows to define different step sizes for the different concepts (i.e. above-ground, below-ground, growth-and-death).
> New time stepper

- TreeModelLib/BelowgroundCompetition/OGS/helpers/CellInformation.py
Update of ogs-helpers in order to allow 2 dimensional input meshes
> [TML] ogs-helper functionality for 2D meshes added

- TreeModelLib/BelowgroundCompetition/OGSLargeScale3D/OGSLargeScale3D.py
There were some minor mistakes...
> [TML/BC/OGS] Bugfixes @mcwimm ;)

- TimeLoopLib/SimpleTimeLoop/SimpleLoop.py
- TimeLoopLib/TreeDynamicTimeLoop.py
- TimeLoopLib/TreeDynamicTimeStepping.py
addressing Issue #136: some reformulation of variable assignement in order to avoid confusions
> [TML] Changing return variable assignement in timestepping

- ProjectLib/Project.py
- TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
- TreeModelLib/BelowgroundCompetition/SymmetricZOI/__init__.py
- TreeModelLib/BelowgroundCompetition/__init__.py
Below-ground competition concept based on BETTINA ODD 2017:
symmetric zone of influence (no salinity)
> [TML] Introduce belowground competition concept 'symmetric ZOI'

- ProjectLib/Project.py
- TreeModelLib/BelowgroundCompetition/SZoiFixedSalinity/SZoiFixedSalinity.py
- TreeModelLib/BelowgroundCompetition/SZoiFixedSalinity/__init__.py
- TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
- TreeModelLib/BelowgroundCompetition/__init__.py
Combination (child) of SymmetricZOI & FixedSalinity; no new functionalities
> Belowground Symmetric ZOI & Fixed Salinity

- Documentation/ProjectFile/MangaProject/tree_output/OneFile/s_output_times.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFile/s_output_times.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTimestepOneFilePerGroup/s_output_times.md
- Documentation/ProjectFile/MangaProject/tree_output/OneTreeOneFile/s_output_times.md
- TreeOutputLib/OneFile/OneFile.py
- TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
- TreeOutputLib/OneTimestepOneFilePerGroup/OneTimestepOneFilePerGroup.py
- TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
- test/smallTests/testSetupsWithoutOGS/smallSetup_5.xml
Array with specific times for output to be written can be provided now.
> Tree output timesteps

- TreeModelLib/GrowthAndDeathDynamics/Mortality/Memory/Memory.py
- TreeModelLib/GrowthAndDeathDynamics/Mortality/NoGrowth/NoGrowth.py
- TreeModelLib/GrowthAndDeathDynamics/Mortality/Random/Random.py
- TreeModelLib/GrowthAndDeathDynamics/Mortality/RandomGrowth/RandomGrowth.py
- TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
- TreeModelLib/TreeModel.py
Getter and setter functions were mixed up.
> Bug fix in mortality concepts

- README.md
- web/config.toml
- web/content/de/_index.html
- web/content/de/docs/Erste_Schritte/Installation.md
- web/content/en/_index.html
- web/content/en/docs/getting_started/Installation.md
With this commit the old name (mangrove-froundwater feedback model) is updated to "PYthon Models for AGeNt-based resource GAthering"
Adressess #200
> Renaming of pyMANGA 

- .github/workflows/main.yml
> update of yml file

- Benchmarks/ExampleSetups/OGSExampleSetup/MakeGrid.py
In this PR is a script added with which you can create a grid out of given (geometric) parameters
> add script for ogs grid

- Benchmarks/ModuleBenchmarks/GrowthAndDeath/Mortality/Memory/Memory.xml
- PlantModelLib/Mortality/Memory/Memory.py
- PlantModelLib/Mortality/NoGrowth/NoGrowth.py
- PlantModelLib/Mortality/Random/Random.py
- PlantModelLib/Mortality/RandomGrowth/RandomGrowth.py
New: use average yearly values instead of sum over time steps
TODOS:
> Bugfix in mortality concept Memory

- Benchmarks/ExampleSetups/FixedSalinityFromFile/FixedSalinity_FromFile_A.xml
... acoording to new control file structure.
> Update FixedSalinity example A

- Benchmarks/ExampleSetups/ExmouthGulf/setup_pymanga.xml
- Benchmarks/ExampleSetups/ExternalSetup/ExternalOGS.xml
- Benchmarks/GenericTests/AllSimple.xml
- Benchmarks/ModuleBenchmarks/TreeOutput/OneFile/OneFile.xml
- Benchmarks/ModuleBenchmarks/TreeOutput/OnePlantOneFile/OnePlantOneFile.xml
- Benchmarks/ModuleBenchmarks/TreeOutput/OnePlantOneFile_2/OnePlantOneFile_2.xml
- Benchmarks/ModuleBenchmarks/TreeOutput/OneTimestepOneFile/OneTimestepOneFile.xml
- Benchmarks/ModuleBenchmarks/TreeOutput/OneTimestepOneFilePerGroup/OneTimestepOneFilePerGroup.xml
Updated the remaining .xml files in the benchmark folder to match the new structure.
FixedSalinity example are already fixed here #264.
> New structure for example files 

- Benchmarks/ExampleSetups/OGSExampleSetup/NetwOGS3D_SAZOI_BETTINA.xml
- Benchmarks/ExampleSetups/OGSExampleSetup/OGS3D_SAZOI_BETTINA.xml
- Benchmarks/ModuleBenchmarks/PlantModules/SimpleKiwi/Belowground/FON/FON_CI.xml
& FON example (but see issue #267 )
> Project file structure updates

- Benchmarks/ExampleSetups/FixedSalinityFromFile/FixedSalinity_FromFile_B.xml
- Benchmarks/ExampleSetups/FixedSalinityFromFile/FixedSalinity_FromFile_C.xml
... according to new structure.
> Update FixedSalinity example B and C

- Benchmarks/ExampleSetups/MergeModules/MergeModules.xml
- ProjectLib/Project.py
- ResourceLib/BelowGround/Generic/Merge/Merge.md
- ResourceLib/BelowGround/Generic/Merge/Merge.py
- ResourceLib/BelowGround/Generic/Merge/__init__.py
- ResourceLib/BelowGround/Generic/__init__.py
Please test and review.
Test file can be found in Benchmarks/ExampleSetups/MergeModules
@jack-w-hill could you please check the doc language?
ToDo: if this works, we can delete SZoiFixedSalinity
> New module to use multiple below-ground modules

- Benchmarks/BenchmarkList.xml
- PlantModelLib/BettinaNetwork/BettinaNetwork.py
- PlantModelLib/Mortality/Memory/Memory.py
- PlantModelLib/Mortality/NoGrowth/NoGrowth.py
- PlantModelLib/Mortality/Random/Random.py
- PlantModelLib/Mortality/RandomGrowth/RandomGrowth.py
- PlantModelLib/PlantModel.py
- PopulationLib/GroupPlanting.py
- ResourceLib/AboveGround/SimpleAsymmetricZOI/SimpleAsymmetricZOI.py
- ResourceLib/BelowGround/Individual/FON/FON.py
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
- ResourceLib/BelowGround/Individual/SymmetricZOI/SymmetricZOI.py
- ResourceLib/BelowGround/Network/Network/Network.py
- ResourceLib/BelowGround/Network/NetworkFixedSalinity/NetworkFixedSalinity.py
- ResourceLib/ResourceModel.py
Function to read information from project file moved to ResourceModel.py.
Can be used by all resource models by providing required tags.
What`s still problematic is the handling of private variables.
At the moment, they are reassigned but another solution would be better.
@jvollhueter  what do you think? Any ideas?
> Method to read prj-file information

- ResourceLib/BelowGround/Individual/FON/FON.py
so far the FON was not calculated if there was no tree-to-tree competition.
& added references for some equations
> Bugfix in FON

- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.md
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
@jvollhueter @zaphod-bx 
based on our discussion this week, I added "cases" to the fixed salinity modules. Would this fit your requirements?
> Introduce cases for fixedsalinity

- Benchmarks/ModuleBenchmarks/PlantModules/SimpleKiwi/Belowground/FON/FON_CI.xml
- ResourceLib/BelowGround/Individual/FON/FON.md
- ResourceLib/BelowGround/Individual/FON/FON.py
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.md
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
> Separate salt stress and tree-to-tree competition in FON

- ModelOutputLib/ModelOutput.md
- ModelOutputLib/__init__.py
- PlantModelLib/Bettina/Bettina.md
build documentation locally:
``py -m pdoc --docformat google -o ./docs ..\pyMANGA\``
> Complete doc for ModelOutput

- PlantModelLib/Bettina/Bettina.md
- PlantModelLib/BettinaNetwork/BettinaNetwork.md
- PlantModelLib/Default/Default.md
- PlantModelLib/Kiwi/Kiwi.md
- PlantModelLib/Kiwi/__init__.py
- ResourceLib/AboveGround/AsymmetricZOI/AsymmetricZOI.md
- ResourceLib/AboveGround/Default/Default.md
- ResourceLib/AboveGround/Default/__init__.py
- ResourceLib/BelowGround/Generic/OGSExternal/__init__.py
- ResourceLib/BelowGround/Generic/__init__.py
- ResourceLib/BelowGround/Individual/SymmetricZOI/SymmetricZOI.md
- ResourceLib/BelowGround/Individual/SymmetricZOI/__init__.py
To build documentation locally, run `py -m pdoc --docformat google --math  -o ./docs ..\pyMANGA\`
@zaphod-bx  Can you have a look at Bettina units?
> Continue documentation

- Benchmarks/ModuleBenchmarks/PlantModules/Bettina/Belowground/FixedSalinity/FixedSalinity.xml
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.md
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
With this extension salinity at each time step is calculated using a sine function.
Here is an example how this would look like:
This shows the avaerage salinity within the model domain. Thin lines represent different model runs.
> Extension of FixedSalinity module

- MANGA.py
Added -l flag for logging to the manga help flag for consistency.
> [Logging] Added log flag to help

- Benchmarks/ModuleBenchmarks/PlantModules/Kiwi/Aboveground/AsymmetricZOI/AsymmetricZOI.xml
- Benchmarks/ModuleBenchmarks/PlantModules/Kiwi/Aboveground/AsymmetricZOI/AsymmetricZOI_CI.xml
- Benchmarks/ModuleBenchmarks/PlantModules/Kiwi/Belowground/Merge_FixedSalinity_sZOI/Merge_FixedSalinity_sZOI.xml
- Benchmarks/ModuleBenchmarks/PlantModules/Kiwi/Belowground/Merge_FixedSalinity_sZOI/Merge_FixedSalinity_sZOI_CI.xml
- Benchmarks/ModuleBenchmarks/PlantModules/Kiwi/Belowground/SymmetricZOI/SymmetricZOI.xml
- Benchmarks/ModuleBenchmarks/PlantModules/Kiwi/Belowground/SymmetricZOI/SymmetricZOI_CI.xml
- PlantModelLib/Kiwi/Kiwi.py
- PopulationLib/Species/AvicenniaKiwi/AvicenniaKiwi.py
- ResourceLib/AboveGround/AsymmetricZOI/AsymmetricZOI.py
- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
- ResourceLib/BelowGround/Individual/SymmetricZOI/SymmetricZOI.py
... in PR #323 we forgot to update the ZOI skripts that check only for Bettina geometry...
I introduced a dirty work around. Need to be fixed when we rename all geometry elements.
> Bugfix previous PR

- .github/workflows/main.yml
- README.md
- requirements.txt
> Test coverage

- PlantModelLib/Mortality/Mortality.py
- PopulationLib/PlantGroup.py
- ProjectLib/Project.py
- ResourceLib/BelowGround/Generic/Merge/Merge.py
I introduced a function to simplify class (module) imports.
With this function we don't need case requests anymore.
@rbnmj this would simplify the instructions as well
> Simplify class imports

- ModelOutputLib/ModelOutput.md
- ModelOutputLib/ModelOutput.py
- TimeLoopLib/DynamicTimeLoop.py
This code update fixes a bug in the function that determines when output is written and simplifies the existing code.
@ChrisWudel : can you please text if this works with different settings.
> Bugfix in model output

- ResourceLib/BelowGround/Individual/SymmetricZOI/SymmetricZOI.py
The following were shows simulations on a small 10x10 patch with different resolutions (i.e., with and withou interpolation):
> Bugfix in ZOI grid interpolation

- ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
- ResourceLib/BelowGround/Individual/SaltFeedbackBucket/SaltFeedbackBucket.py
In two salinity modules all growth_concept_information was overwritten. Now this dictionary get's updated instead.
> Bugfix to write plant age as output 

- PopulationLib/Dispersal/Distance2Parent/Distance2Parent.md
- PopulationLib/Dispersal/Distance2Parent/Distance2Parent.py
Updated Distance2Parent weibull and doc
> Updated Distance2Parent

- PlantModelLib/Mortality/Memory/Memory.md
Small error in doc mortality module memory
> Small fix doc memory module
